### ISSUE TITLE
Adjust Milestone 1 Deliverables

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#40]
- [ ] Requirements
- [ ] Example Story Contents
- [ ] Mock ups (Mobile, New Frontend Web, Timeline)
- [ ] Team Details
- [ ] What we did
- [ ] What we will do until milestone 2
- [ ] Activity Feed Details (New post by following, Follow, Like story, Comment story)

**Comment by dbaslan** [comment]
Will add memory creation and viewing to the deliverable features for web (not mobile)

**Comment by dbaslan** [comment]
Wrote down the deliverables on the wiki and the milestone page. Please review @SWE574-Fall2023-Group1/backend

**Comment by ckertam** [comment]
Can we tag deliverables in this issue so we can see them easily? @dbaslan 
And please inform everyone to check it from discord. Not only backend team for sure 🥂

**Comment by dbaslan** [comment]
@SWE574-Fall2023-Group1/all  The deliverables can be found [here](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki/Milestones), and the report is [here](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/blob/main/Documents/Swe574_2023_Fall_M1Deliverables_.pdf)

**Comment by dbaslan** [comment]
The deliverables have been adjusted, consult the instructions and the report for clarification, closing.
